# Generated by Django 4.2.10 on 2024-05-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, unique=True)),
                ('db_name', models.CharField(max_length=255)),
                ('db_user', models.CharField(max_length=255)),
                ('db_password', models.CharField(max_length=255)),
                ('db_host', models.CharField(max_length=255)),
                ('db_port', models.CharField(max_length=255)),
            ],
        ),
    ]
