from rest_framework import serializers

class mralAchievementsSerializer(serializers.Serializer):
    stockpile     = serializers.CharField()
    pile_id       = serializers.CharField()
    nama_material = serializers.CharField()
    total_ore     = serializers.FloatField()
    incomplete    = serializers.FloatField()
    unprepared    = serializers.FloatField()
    unreleased    = serializers.FloatField()
    released      = serializers.FloatField()
    recovery      = serializers.CharField()
    Ni            = serializers.FloatField()
    Co            = serializers.FloatField()
    Fe2O3         = serializers.FloatField()
    Fe            = serializers.FloatField()
    Mgo           = serializers.FloatField()
    SiO2          = serializers.FloatField()
    Sm            = serializers.FloatField()


    def to_representation(self, instance):
        # Gunakan format() untuk dua angka di belakang koma
        instance['Ni']    = "{:.2f}".format(instance['Ni'])
        instance['Co']    = "{:.2f}".format(instance['Co'])
        instance['Fe2O3'] = "{:.2f}".format(instance['Fe2O3'])
        instance['Fe']    = "{:.2f}".format(instance['Fe'])
        instance['Mgo']   = "{:.2f}".format(instance['Mgo'])
        instance['SiO2']  = "{:.2f}".format(instance['SiO2'])
        instance['Sm']    = "{:.2f}".format(instance['Sm'])
        instance['total_ore']  = round(instance['total_ore'], 2)
        instance['incomplete'] = round(instance['incomplete'], 2)
        instance['unprepared'] = round(instance['unprepared'], 2)
        instance['unreleased'] = round(instance['unreleased'], 2)
        instance['released']   = round(instance['released'], 2)
        return super().to_representation(instance)
    
class roaAchievementsSerializer(serializers.Serializer):
    stockpile     = serializers.CharField()
    pile_id       = serializers.CharField()
    nama_material = serializers.CharField()
    total_ore     = serializers.FloatField()
    incomplete    = serializers.FloatField()
    unprepared    = serializers.FloatField()
    unreleased    = serializers.FloatField()
    released      = serializers.FloatField()
    recovery      = serializers.CharField()
    Ni            = serializers.FloatField()
    Co            = serializers.FloatField()
    Al2O3         = serializers.FloatField()
    CaO           = serializers.FloatField()
    Cr2O3         = serializers.FloatField()
    Fe2O3         = serializers.FloatField()
    Fe            = serializers.FloatField()
    Mgo           = serializers.FloatField()
    SiO2          = serializers.FloatField() 
    Mc            = serializers.FloatField() 
    Sm            = serializers.FloatField()
   
   
    def to_representation(self, instance):
        # Gunakan format() untuk dua angka di belakang koma
        instance['Ni']    = "{:.2f}".format(instance['Ni'])
        instance['Co']    = "{:.2f}".format(instance['Co'])
        instance['Al2O3'] = "{:.2f}".format(instance['Al2O3'])
        instance['CaO']   = "{:.2f}".format(instance['CaO'])
        instance['Cr2O3'] = "{:.2f}".format(instance['Cr2O3'])
        instance['Fe2O3'] = "{:.2f}".format(instance['Fe2O3'])
        instance['Fe']    = "{:.2f}".format(instance['Fe'])
        instance['Mgo']   = "{:.2f}".format(instance['Mgo'])
        instance['SiO2']  = "{:.2f}".format(instance['SiO2'])
        instance['Mc']    = "{:.2f}".format(instance['Mc'])
        instance['Sm']    = "{:.2f}".format(instance['Sm'])
        instance['total_ore']  = round(instance['total_ore'], 2)
        instance['incomplete'] = round(instance['incomplete'], 2)
        instance['unprepared'] = round(instance['unprepared'], 2)
        instance['unreleased'] = round(instance['unreleased'], 2)
        instance['released']   = round(instance['released'], 2)
        return super().to_representation(instance)
    